// The one typed seam between the frontend and the Rust commands.
//
// `commands` in `src/bindings/index.ts` is generated by tauri-specta from
// the Rust command signatures (regenerated on every `cargo test`), so the
// command name, every argument, and the result type are all compiler
// checked here: a misspelled command or a wrong/missing argument fails
// `npm run build`. Hooks and components call the backend only through
// `invokeTauri`; tests mock this module.
//
// Invocation fails loudly when the app runs outside a Tauri webview (plain
// `npm run dev` in a browser) instead of hanging on a missing IPC bridge.
//
// Fixture mode (`npm run dev:fixture`, dev-only): `VITE_MOCK_BACKEND` is a
// compile-time constant (`vite.config.ts`), so production builds fold every
// branch below to false and the dynamically imported fixture backend
// (`src/fixtures/`) never enters the bundle. In fixture mode the app counts
// as running in Tauri: `src/fixtures` answers commands and stands in for the
// webview's native IPC before the first render (`src/main.tsx`).

import { commands } from "../bindings";

const fixtureMode = import.meta.env.VITE_MOCK_BACKEND === "1";

export const isTauri =
  fixtureMode ||
  (typeof window !== "undefined" &&
    Boolean(
      (window as { __TAURI__?: unknown }).__TAURI__ ||
        (window as { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__,
    ));

/** The generated command table: `keyof Commands` is the set of valid names. */
export type Commands = typeof commands;

/** Name of one backend command, as exposed by the generated bindings. */
export type CommandName = keyof Commands;

/** The typed seam's own signature, for components that receive it as a prop. */
export type InvokeTauri = <K extends CommandName>(
  command: K,
  ...args: Parameters<Commands[K]>
) => ReturnType<Commands[K]>;

export const invokeTauri: InvokeTauri = <K extends CommandName>(
  command: K,
  ...args: Parameters<Commands[K]>
) => {
  type Result = ReturnType<Commands[K]>;
  if (fixtureMode) {
    return import("../fixtures").then(({ fixtureInvoke }) =>
      fixtureInvoke(command, ...args),
    ) as Result;
  }
  if (!isTauri) {
    return Promise.reject(new Error("Tauri API is not available")) as Result;
  }
  const fn = commands[command] as (...fnArgs: typeof args) => Result;
  return fn(...args);
};
