// IPC DTO types are generated by ts-rs from the Rust structs into
// src/bindings/ (regenerated by `cargo test`, committed, CI diff-guarded).
// This shim is the single import home for the projects world: components
// import from here, never from src/bindings/ directly.

export type { ProjectDto } from "../../bindings/ProjectDto";
export type { ProjectToolDto } from "../../bindings/ProjectToolDto";
export type { ProjectSkillAssignmentDto } from "../../bindings/ProjectSkillAssignmentDto";
export type { ResyncSummaryDto } from "../../bindings/ResyncSummaryDto";
export type { BulkAssignResultDto } from "../../bindings/BulkAssignResultDto";
export type { BulkAssignErrorDto } from "../../bindings/BulkAssignErrorDto";
export type { GitignoreStatusDto } from "../../bindings/GitignoreStatusDto";
