// IPC DTO types are generated by tauri-specta from the Rust structs into
// src/bindings/index.ts (regenerated by `cargo test`, committed, CI
// diff-guarded).
// This shim is the single import home for the projects world: components
// import from here, never from src/bindings/ directly.

export type { CommandError } from "../../bindings";
export type { ProjectDto } from "../../bindings";
export type { ProjectToolDto } from "../../bindings";
export type { ProjectSkillAssignmentDto } from "../../bindings";
export type { ProjectSyncStatus } from "../../bindings";
export type { SyncStatus } from "../../bindings";
export type { SyncMode } from "../../bindings";
export type { ResyncSummaryDto } from "../../bindings";
export type { BulkAssignResultDto } from "../../bindings";
export type { BulkAssignErrorDto } from "../../bindings";
export type { GitignoreStatusDto } from "../../bindings";
export type { IgnoreUpdateOptions } from "../../bindings";
