//! The Rust→TS command error contract.
//!
//! Every `#[tauri::command]` returns `Result<T, CommandError>`; Tauri
//! serializes the `Err` payload as structured JSON, so the frontend receives
//! `{ "code": "TOOL_NOT_WRITABLE", "tool": "...", "path": "..." }` instead of
//! a pipe-prefixed string. The TS mirror is generated by tauri-specta into
//! `src/bindings/index.ts` (regenerated on every `cargo test`); the single frontend
//! consumer is `describeCommandError` in `src/commandError.ts`, which owns all
//! user-facing copy (EN & ZH). Backend composes no user-facing prose beyond
//! the `Other` fallback's raw error chain.
//!
//! Adding a variant is a two-compiler change: the Rust variant here, the
//! regenerated TS union, and a branch in `describeCommandError`.

use serde::Serialize;
use specta::Type;

use crate::core::errors::SignalError;
use crate::core::global_sync::GlobalSyncError;

/// Why a GitHub clone/fetch failed, classified backend-side from the error
/// chain (the backend has the chain; the frontend owns the copy).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum GitCloneFailureKind {
    Tls,
    Auth,
    NotFound,
    Dns,
    Timeout,
    Refused,
    /// Running the system `git` CLI itself failed (fallback disabled).
    ExecFailed,
    Unknown,
}

/// Structured command failure crossing the IPC seam.
#[derive(Debug, Clone, Serialize, Type)]
#[serde(
    tag = "code",
    rename_all = "SCREAMING_SNAKE_CASE",
    rename_all_fields = "camelCase"
)]
pub enum CommandError {
    ToolNotInstalled {
        tool: String,
    },
    TargetExists {
        path: String,
    },
    ToolNotWritable {
        tool: String,
        path: String,
    },
    SkillInvalid {
        reason: String,
    },
    MultiSkills,
    SkillExists {
        /// Name of the skill directory already present in the central repo.
        name: String,
    },
    DuplicateProject {
        path: String,
    },
    AssignmentExists {
        project: String,
        skill: String,
        tool: String,
    },
    NotFound {
        kind: String,
        id: String,
    },
    Cancelled,
    RateLimited {
        /// Rounded-up minutes until the limit resets; 0 = unknown.
        reset_minutes: i64,
    },
    GitCloneFailed {
        kind: GitCloneFailureKind,
        detail: String,
    },
    GithubSkillNotFound {
        /// Human-checkable GitHub tree URL for the missing skill path.
        url: String,
    },
    DeleteCleanupFailed {
        /// `"<path>: <io error>"` diagnostics per failed cleanup target.
        failures: Vec<String>,
    },
    Other {
        message: String,
    },
}

impl CommandError {
    /// Wrap an infrastructure failure (e.g. a task join error) as `Other`.
    pub fn internal(err: impl std::fmt::Display) -> Self {
        CommandError::Other {
            message: err.to_string(),
        }
    }

    /// Classify an `anyhow` chain into the wire contract. This is the single
    /// seam where core errors become frontend-visible: typed `SignalError`s
    /// are recovered by downcast, GitHub clone failures are classified by
    /// heuristic, and everything else becomes `Other` with the full chain.
    pub fn from_anyhow(err: anyhow::Error) -> Self {
        let err = match err.downcast::<SignalError>() {
            Ok(signal) => return CommandError::from(signal),
            Err(err) => err,
        };
        let err = match err.downcast::<GlobalSyncError>() {
            Ok(sync_err) => return CommandError::from(sync_err),
            Err(err) => err,
        };

        let full = format!("{:#}", err);
        let root = err.root_cause().to_string();
        let lower = full.to_lowercase();

        // GitHub clone/fetch failures: classify so the frontend can show a
        // localized hint instead of a raw git error chain.
        if lower.contains("github.com")
            && (lower.contains("clone ") || lower.contains("remote") || lower.contains("fetch"))
        {
            let kind = if lower.contains("securetransport") {
                GitCloneFailureKind::Tls
            } else if lower.contains("authentication")
                || lower.contains("permission denied")
                || lower.contains("credentials")
            {
                GitCloneFailureKind::Auth
            } else if lower.contains("not found") {
                GitCloneFailureKind::NotFound
            } else if lower.contains("failed to resolve")
                || lower.contains("could not resolve")
                || lower.contains("dns")
            {
                GitCloneFailureKind::Dns
            } else if lower.contains("timed out") || lower.contains("timeout") {
                GitCloneFailureKind::Timeout
            } else if lower.contains("connection refused") || lower.contains("connection reset") {
                GitCloneFailureKind::Refused
            } else {
                GitCloneFailureKind::Unknown
            };
            return CommandError::GitCloneFailed { kind, detail: root };
        }

        // Redact noisy temp paths from clone context (we care about the cause,
        // not the destination). Example head line:
        // `clone https://... into "/Users/.../skills-hub-git-<uuid>"`
        let mut message = full;
        if let Some(head) = message.lines().next() {
            if head.starts_with("clone ") {
                if let Some(pos) = head.find(" into ") {
                    let head_redacted = head[..pos].to_string();
                    let rest: String = message.lines().skip(1).collect::<Vec<_>>().join("\n");
                    message = if rest.is_empty() {
                        head_redacted
                    } else {
                        format!("{}\n{}", head_redacted, rest)
                    };
                }
            }
        }

        CommandError::Other { message }
    }
}

impl From<SignalError> for CommandError {
    fn from(signal: SignalError) -> Self {
        match signal {
            SignalError::Cancelled => CommandError::Cancelled,
            SignalError::RateLimited { reset_minutes } => {
                CommandError::RateLimited { reset_minutes }
            }
            SignalError::SkillInvalid { reason } => CommandError::SkillInvalid { reason },
            SignalError::MultiSkills => CommandError::MultiSkills,
            SignalError::SkillExists { name } => CommandError::SkillExists { name },
            SignalError::DuplicateProject { path } => CommandError::DuplicateProject { path },
            SignalError::AssignmentExists {
                project,
                skill,
                tool,
            } => CommandError::AssignmentExists {
                project,
                skill,
                tool,
            },
            SignalError::NotFound { kind, id } => CommandError::NotFound { kind, id },
            SignalError::GitExecFailed { detail } => CommandError::GitCloneFailed {
                kind: GitCloneFailureKind::ExecFailed,
                detail,
            },
            SignalError::GitTimeout { detail } => CommandError::GitCloneFailed {
                kind: GitCloneFailureKind::Timeout,
                detail,
            },
            SignalError::GithubSkillNotFound { url } => CommandError::GithubSkillNotFound { url },
            SignalError::DeleteCleanupFailed { failures } => {
                CommandError::DeleteCleanupFailed { failures }
            }
        }
    }
}

impl From<GlobalSyncError> for CommandError {
    fn from(err: GlobalSyncError) -> Self {
        match err {
            GlobalSyncError::ToolNotInstalled { tool_key } => {
                CommandError::ToolNotInstalled { tool: tool_key }
            }
            GlobalSyncError::TargetExists { target_path } => CommandError::TargetExists {
                path: target_path.to_string_lossy().to_string(),
            },
            GlobalSyncError::ToolNotWritable {
                tool_display_name,
                skills_dir,
            } => CommandError::ToolNotWritable {
                tool: tool_display_name,
                path: skills_dir.to_string_lossy().to_string(),
            },
            GlobalSyncError::Other(err) => CommandError::from_anyhow(err),
        }
    }
}

impl std::fmt::Display for CommandError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Debug-ish display for logs; user-facing copy lives frontend-side.
        match serde_json::to_string(self) {
            Ok(json) => write!(f, "{}", json),
            Err(_) => write!(f, "{:?}", self),
        }
    }
}
