// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsBounds } from "./SettingsBounds";

/**
 * Snapshot of every backend-persisted setting, already parsed, defaulted
 * and (for the central repo path) resolved.
 */
export type AppSettings = { 
/**
 * Resolved central skills repo root (override or default).
 */
central_repo_path: string, git_cache_cleanup_days: number, git_cache_ttl_secs: number, 
/**
 * Empty string when no token is stored.
 */
github_token: string, auto_sync_enabled: boolean, 
/**
 * `None` = never configured (distinct from an empty selection).
 */
global_selected_tools: Array<string> | null, scan_selected_tools_only: boolean, ui_zoom_level: number, bounds: SettingsBounds, };
