// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One skill in a batch sync request.
 */
export type BatchSyncSkillDto = { skill_id: string, name: string, source_path: string, };
