// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchSyncOverrideDto } from "./BatchSyncOverrideDto";

export type BatchSyncPolicyDto = { overwrite: boolean, overwrite_if_same_content: boolean, overrides: Array<BatchSyncOverrideDto>, };
