// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Force-overwrite for one (skill, tool) pair; applies to any target tool
 * sharing the named tool's skills dir.
 */
export type BatchSyncOverrideDto = { skill_id: string, tool: string, overwrite: boolean, };
