// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncTargetResultDto } from "./SyncTargetResultDto";

export type BatchSyncReportDto = { results: Array<SyncTargetResultDto>, synced: number, skipped: number, failed: number, };
