// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkAssignErrorDto } from "./BulkAssignErrorDto";
import type { ProjectSkillAssignmentDto } from "./ProjectSkillAssignmentDto";

export type BulkAssignResultDto = { assigned: Array<ProjectSkillAssignmentDto>, failed: Array<BulkAssignErrorDto>, };
