// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire form of [`SkillMatch`]: candidates are referenced by subpath, the
 * identity the frontend already keys its selection by.
 */
export type CandidateMatch = { "kind": "resolved", subpath: string, } | { "kind": "ambiguous", subpaths: Array<string>, } | { "kind": "none" };
