// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeaturedSkillDto = { slug: string, name: string, summary: string, downloads: number, stars: number, source_url: string, };
