// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a GitHub clone/fetch failed, classified backend-side from the error
 * chain (the backend has the chain; the frontend owns the copy).
 */
export type GitCloneFailureKind = "tls" | "auth" | "notFound" | "dns" | "timeout" | "refused" | "unknown";
