// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateMatch } from "./CandidateMatch";
import type { GitSkillCandidate } from "./GitSkillCandidate";

/**
 * What the git add flow gets back from a listing: the candidates plus, when
 * the caller named the skill it is after (Explore install), that name
 * resolved against them by the one core matching rule.
 */
export type GitSkillListing = { candidates: Array<GitSkillCandidate>, 
/**
 * `None` when no `target_name` was given.
 */
target_match: CandidateMatch | null, };
