// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalToolConfigDto = { selected_tools: Array<string> | null, scan_selected_only: boolean, };
