// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two toggles behind `update_project_gitignore`; also the optional
 * ignore intent carried by `configure_project_tools`, hence an IPC DTO.
 */
export type IgnoreUpdateOptions = { add_to_gitignore: boolean, add_to_exclude: boolean, };
