// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
	/**
	 *  Persist one setting and return the effective snapshot. `~` in a central
	 *  repo path is expanded here — the only environment-aware step — before
	 *  the policy layer validates and applies it.
	 */
	updateSetting: (update: SettingUpdate) => __TAURI_INVOKE<AppSettings>("update_setting", { update }),
	getToolStatus: () => __TAURI_INVOKE<ToolStatusDto>("get_tool_status"),
	getProjectToolStatus: () => __TAURI_INVOKE<ToolStatusDto>("get_project_tool_status"),
	clearGitCacheNow: () => __TAURI_INVOKE<number>("clear_git_cache_now"),
	getOnboardingPlan: () => __TAURI_INVOKE<OnboardingPlan>("get_onboarding_plan"),
	listLocalSkillsCmd: (basePath: string) => __TAURI_INVOKE<LocalSkillCandidate[]>("list_local_skills_cmd", { basePath }),
	installLocalSelection: (basePath: string, subpath: string, name: string | null) => __TAURI_INVOKE<InstallResultDto>("install_local_selection", { basePath, subpath, name }),
	listGitSkillsCmd: (repoUrl: string, targetName: string | null) => __TAURI_INVOKE<GitSkillListing>("list_git_skills_cmd", { repoUrl, targetName }),
	installGitSelection: (repoUrl: string, subpath: string, name: string | null) => __TAURI_INVOKE<InstallResultDto>("install_git_selection", { repoUrl, subpath, name }),
	/**
	 *  Sync N skills to M tools in one call. The backend owns the whole
	 *  choreography — installedness filtering, shared-dir dedupe, overwrite
	 *  policy, DB record fan-out — and returns a per-target report; per-target
	 *  failures are data, not command errors.
	 */
	syncSkillsToTools: (skills: BatchSyncSkillDto[], tools: string[], policy: BatchSyncPolicyDto, onProgress: Channel<SyncProgressDto>) => __TAURI_INVOKE<BatchSyncReportDto>("sync_skills_to_tools", { skills, tools, policy, onProgress }),
	unsyncSkillFromTool: (skillId: string, tool: string) => __TAURI_INVOKE<null>("unsync_skill_from_tool", { skillId, tool }),
	updateManagedSkill: (skillId: string) => __TAURI_INVOKE<UpdateResultDto>("update_managed_skill", { skillId }),
	importExistingSkill: (sourcePath: string, name: string | null) => __TAURI_INVOKE<InstallResultDto>("import_existing_skill", { sourcePath, name }),
	removeSkillSource: (path: string) => __TAURI_INVOKE<null>("remove_skill_source", { path }),
	getManagedSkills: () => __TAURI_INVOKE<ManagedSkillDto[]>("get_managed_skills"),
	deleteManagedSkill: (skillId: string) => __TAURI_INVOKE<null>("delete_managed_skill", { skillId }),
	unsyncAllSkills: () => __TAURI_INVOKE<number>("unsync_all_skills"),
	unsyncSkill: (skillId: string) => __TAURI_INVOKE<number>("unsync_skill", { skillId }),
	getFeaturedSkills: () => __TAURI_INVOKE<FeaturedSkillDto[]>("get_featured_skills"),
	searchSkillsOnline: (query: string, limit: number | null) => __TAURI_INVOKE<OnlineSkillDto[]>("search_skills_online", { query, limit }),
	listSkillFiles: (centralPath: string) => __TAURI_INVOKE<SkillFileEntry[]>("list_skill_files", { centralPath }),
	readSkillFile: (centralPath: string, filePath: string) => __TAURI_INVOKE<string>("read_skill_file", { centralPath, filePath }),
	cloneExploreSkill: (sourceUrl: string, skillName: string | null) => __TAURI_INVOKE<string>("clone_explore_skill", { sourceUrl, skillName }),
	hideExploreSkill: (sourceUrl: string) => __TAURI_INVOKE<null>("hide_explore_skill", { sourceUrl }),
	unhideExploreSkill: (sourceUrl: string) => __TAURI_INVOKE<null>("unhide_explore_skill", { sourceUrl }),
	getHiddenExploreSkills: () => __TAURI_INVOKE<string[]>("get_hidden_explore_skills"),
	cancelCurrentOperation: () => __TAURI_INVOKE<null>("cancel_current_operation"),
	registerProject: (path: string) => __TAURI_INVOKE<ProjectDto>("register_project", { path }),
	removeProject: (projectId: string) => __TAURI_INVOKE<null>("remove_project", { projectId }),
	listProjects: () => __TAURI_INVOKE<ProjectDto[]>("list_projects"),
	updateProjectPath: (projectId: string, path: string) => __TAURI_INVOKE<ProjectDto>("update_project_path", { projectId, path }),
	/**
	 *  Replace the project's configured tool set and, when `gitignore` is given,
	 *  update its ignore files afterwards. Core owns the ordering
	 *  (`project_ops::configure_project_tools`); returns the resulting tools.
	 */
	configureProjectTools: (projectId: string, tools: string[], gitignore: {
	add_to_gitignore: boolean,
	add_to_exclude: boolean,
} | null) => __TAURI_INVOKE<ProjectToolDto[]>("configure_project_tools", { projectId, tools, gitignore }),
	listProjectTools: (projectId: string) => __TAURI_INVOKE<ProjectToolDto[]>("list_project_tools", { projectId }),
	addProjectSkillAssignment: (projectId: string, skillId: string, tool: string) => __TAURI_INVOKE<ProjectSkillAssignmentDto>("add_project_skill_assignment", { projectId, skillId, tool }),
	removeProjectSkillAssignment: (projectId: string, skillId: string, tool: string) => __TAURI_INVOKE<null>("remove_project_skill_assignment", { projectId, skillId, tool }),
	listProjectSkillAssignments: (projectId: string) => __TAURI_INVOKE<ProjectAssignmentListingDto>("list_project_skill_assignments", { projectId }),
	resyncProject: (projectId: string) => __TAURI_INVOKE<ResyncSummaryDto>("resync_project", { projectId }),
	resyncAllProjects: () => __TAURI_INVOKE<ResyncSummaryDto[]>("resync_all_projects"),
	bulkAssignSkill: (projectId: string, skillId: string) => __TAURI_INVOKE<BulkAssignResultDto>("bulk_assign_skill", { projectId, skillId }),
	updateProjectGitignore: (projectId: string, gitignore: IgnoreUpdateOptions) => __TAURI_INVOKE<null>("update_project_gitignore", { projectId, gitignore }),
	getProjectGitignoreStatus: (projectId: string) => __TAURI_INVOKE<GitignoreStatusDto>("get_project_gitignore_status", { projectId }),
};

/* Types */
/**
 *  Snapshot of every backend-persisted setting, already parsed, defaulted
 *  and (for the central repo path) resolved.
 */
export type AppSettings = {
	/**  Resolved central skills repo root (override or default). */
	central_repo_path: string,
	git_cache_cleanup_days: number,
	git_cache_ttl_secs: number,
	/**  Empty string when no token is stored. */
	github_token: string,
	auto_sync_enabled: boolean,
	/**  `None` = never configured (distinct from an empty selection). */
	global_selected_tools: string[] | null,
	scan_selected_tools_only: boolean,
	/**
	 *  Always finite (clamped into `UI_ZOOM_LEVEL_RANGE`), hence `number`
	 *  rather than specta's default `number | null` for `f64`.
	 */
	ui_zoom_level: number,
	bounds: SettingsBounds,
};

/**
 *  Force-overwrite for one (skill, tool) pair; applies to any target tool
 *  sharing the named tool's skills dir.
 */
export type BatchSyncOverrideDto = {
	skill_id: string,
	tool: string,
	overwrite: boolean,
};

export type BatchSyncPolicyDto = {
	overwrite?: boolean,
	overwrite_if_same_content?: boolean,
	overrides?: BatchSyncOverrideDto[],
};

export type BatchSyncReportDto = {
	results: SyncTargetResultDto[],
	synced: number,
	skipped: number,
	failed: number,
};

/**  One skill in a batch sync request. */
export type BatchSyncSkillDto = {
	skill_id: string,
	name: string,
	source_path: string,
};

export type BulkAssignErrorDto = {
	tool: string,
	error: CommandError,
};

export type BulkAssignResultDto = {
	assigned: ProjectSkillAssignmentDto[],
	failed: BulkAssignErrorDto[],
};

/**
 *  Wire form of [`SkillMatch`]: candidates are referenced by subpath, the
 *  identity the frontend already keys its selection by.
 */
export type CandidateMatch = { kind: "resolved"; subpath: string } | { kind: "ambiguous"; subpaths: string[] } | { kind: "none" };

/**  Structured command failure crossing the IPC seam. */
export type CommandError = { code: "TOOL_NOT_INSTALLED"; tool: string } | { code: "TARGET_EXISTS"; path: string } | { code: "TOOL_NOT_WRITABLE"; tool: string; path: string } | { code: "SKILL_INVALID"; reason: string } | { code: "MULTI_SKILLS" } | { code: "SKILL_EXISTS"; 
/**  Name of the skill directory already present in the central repo. */
name: string } | { code: "DUPLICATE_PROJECT"; path: string } | { code: "ASSIGNMENT_EXISTS"; project: string; skill: string; tool: string } | { code: "NOT_FOUND"; kind: string; id: string } | { code: "UNKNOWN_TOOL"; 
/**  Registry key that matched no tool adapter. */
tool: string } | { code: "INVALID_PATH"; path: string; 
/**  Machine token (`missing` / `not_a_directory`) the frontend localizes. */
reason: string } | { code: "CANCELLED" } | { code: "RATE_LIMITED"; 
/**  Rounded-up minutes until the limit resets; 0 = unknown. */
resetMinutes: number } | { code: "GIT_CLONE_FAILED"; kind: GitCloneFailureKind; detail: string } | { code: "GITHUB_SKILL_NOT_FOUND"; 
/**  Human-checkable GitHub tree URL for the missing skill path. */
url: string } | { code: "DELETE_CLEANUP_FAILED"; 
/**  `"<path>: <io error>"` diagnostics per failed cleanup target. */
failures: string[] } | { code: "OTHER"; message: string };

export type FeaturedSkillDto = {
	slug: string,
	name: string,
	summary: string,
	downloads: number,
	stars: number,
	source_url: string,
};

/**
 *  Inclusive float bound, shipped to the frontend inside `AppSettings`.
 * 
 *  specta types `f64` as `number | null` because serde_json writes
 *  NaN/±Infinity as `null`; these bounds are finite constants, so the
 *  field-level override asserts the plain `number` the frontend clamps with.
 */
export type FloatRange = {
	min: number,
	max: number,
};

/**
 *  Why a GitHub clone/fetch failed, classified backend-side from the error
 *  chain (the backend has the chain; the frontend owns the copy).
 */
export type GitCloneFailureKind = "tls" | "auth" | "notFound" | "dns" | "timeout" | "refused" | 
/**  Running the system `git` CLI itself failed (fallback disabled). */
"execFailed" | "unknown";

export type GitSkillCandidate = {
	name: string,
	description: string | null,
	subpath: string,
};

/**
 *  What the git add flow gets back from a listing: the candidates plus, when
 *  the caller named the skill it is after (Explore install), that name
 *  resolved against them by the one core matching rule.
 */
export type GitSkillListing = {
	candidates: GitSkillCandidate[],
	/**  `None` when no `target_name` was given. */
	target_match: CandidateMatch | null,
};

export type GitignoreStatusDto = {
	in_gitignore: boolean,
	in_exclude: boolean,
};

/**
 *  The two toggles behind `update_project_gitignore`; also the optional
 *  ignore intent carried by `configure_project_tools`, hence an IPC DTO.
 */
export type IgnoreUpdateOptions = {
	add_to_gitignore: boolean,
	add_to_exclude: boolean,
};

export type InstallResultDto = {
	skill_id: string,
	name: string,
	central_path: string,
	content_hash: string | null,
};

/**  Inclusive integer bound, shipped to the frontend inside `AppSettings`. */
export type IntRange = {
	min: number,
	max: number,
};

/**
 *  Who may invoke a skill, derived from its `SKILL.md` frontmatter.
 * 
 *  Two Claude Code frontmatter keys govern this (the agentskills.io
 *  specification does not define them yet):
 *  `disable-model-invocation: true` blocks automatic model invocation, and
 *  `user-invocable: false` hides the skill from the `/` menu. Both default to
 *  the permissive value, so a skill with no frontmatter — or with malformed
 *  frontmatter — is [`InvocationMode::UserAndModel`]. Setting both keys is the
 *  documented recipe for hiding a skill from everyone: [`InvocationMode::Neither`].
 */
export type InvocationMode = 
/**  Default: the user can type `/name` and the model can load it on its own. */
"user-and-model" | 
/**  `disable-model-invocation: true` — only the user can invoke it. */
"user-only" | 
/**  `user-invocable: false` — only the model can invoke it. */
"model-only" | 
/**  Both keys restrict invocation — neither the user nor the model can invoke it. */
"neither";

export type LocalSkillCandidate = {
	name: string,
	description: string | null,
	subpath: string,
	valid: boolean,
	reason: string | null,
};

export type ManagedSkillDto = {
	id: string,
	name: string,
	description: string | null,
	source_type: string,
	source_ref: string | null,
	central_path: string,
	created_at: number,
	updated_at: number,
	last_sync_at: number | null,
	status: string,
	/**
	 *  Who may invoke the skill, read from the central copy's `SKILL.md`
	 *  frontmatter at list time (not persisted).
	 */
	invocation_mode: InvocationMode,
	targets: SkillTargetDto[],
};

export type OnboardingGroup = {
	name: string,
	variants: OnboardingVariant[],
	has_conflict: boolean,
};

export type OnboardingPlan = {
	total_tools_scanned: number,
	total_skills_found: number,
	groups: OnboardingGroup[],
};

export type OnboardingVariant = {
	tool: string,
	name: string,
	path: string,
	fingerprint: string | null,
	is_link: boolean,
	link_target: string | null,
};

export type OnlineSkillDto = {
	name: string,
	installs: number,
	source: string,
	source_url: string,
};

/**
 *  A project's assignment rows plus whether the reconcile pass ran.
 * 
 *  `reconciled == false` means a Sync-target mutation was in flight and the
 *  listing skipped reconciliation rather than queue behind it: the rows are
 *  the stored ones. Consumers must not read that as healthy.
 */
export type ProjectAssignmentListingDto = {
	assignments: ProjectSkillAssignmentDto[],
	reconciled: boolean,
};

export type ProjectDto = {
	id: string,
	path: string,
	name: string,
	created_at: number,
	updated_at: number,
	tool_count: number,
	skill_count: number,
	assignment_count: number,
	sync_status: ProjectSyncStatus,
	path_exists: boolean,
};

export type ProjectSkillAssignmentDto = {
	id: string,
	project_id: string,
	skill_id: string,
	skill_name: string,
	tool: string,
	mode: SyncMode,
	status: SyncStatus,
	last_error: string | null,
	synced_at: number | null,
	content_hash: string | null,
	created_at: number,
};

/**
 *  Roll-up of a project's assignments as shown on the project list.
 *  `Missing` folds into `Error` (both need the user's attention).
 */
export type ProjectSyncStatus = 
/**  No assignments at all. */
"none" | "error" | "stale" | "pending" | "synced";

export type ProjectToolDto = {
	id: string,
	project_id: string,
	tool: string,
};

export type ResyncSummaryDto = {
	project_id: string,
	synced: number,
	failed: number,
	errors: string[],
};

/**  One setting write, as sent by the frontend: `{ key, value }`. */
export type SettingUpdate = 
/**
 *  Absolute path; `~` expansion happens at the command seam. Moving the
 *  repo relocates every managed skill directory.
 */
{ key: "central_repo_path"; value: string } | 
/**  Clamped into `GIT_CACHE_CLEANUP_DAYS_RANGE`. */
{ key: "git_cache_cleanup_days"; value: number } | 
/**  Clamped into `GIT_CACHE_TTL_SECS_RANGE`. */
{ key: "git_cache_ttl_secs"; value: number } | 
/**  Trimmed; blank clears the token. */
{ key: "github_token"; value: string } | { key: "auto_sync_enabled"; value: boolean } | { key: "global_tool_config"; value: {
	selected_tools: string[],
	scan_selected_only: boolean,
} } | 
/**
 *  Clamped into `UI_ZOOM_LEVEL_RANGE`; non-finite falls back to default.
 *  Typed `number` (not specta's `number | null` for `f64`): `null` would
 *  fail deserialization, so it is not a value the frontend may send.
 */
{ key: "ui_zoom_level"; value: number };

/**  Every bound the frontend needs to clamp input before sending it. */
export type SettingsBounds = {
	git_cache_cleanup_days: IntRange,
	git_cache_ttl_secs: IntRange,
	ui_zoom_level: FloatRange,
};

export type SkillFileEntry = {
	path: string,
	size: number,
};

export type SkillTargetDto = {
	tool: string,
	mode: SyncMode,
	status: SyncStatus,
	target_path: string,
	synced_at: number | null,
};

/**
 *  How an artifact was materialised. Stored on the row so a later pass knows
 *  whether content drift is possible (copies) or not (links).
 */
export type SyncMode = "symlink" | 
/**  Windows directory junction (the symlink fallback). */
"junction" | "copy";

/**
 *  Progress tick streamed over the command's channel before each attempted
 *  (skill, tool) pair.
 */
export type SyncProgressDto = {
	index: number,
	total: number,
	skill_name: string,
	tool: string,
};

/**  Lifecycle of one synced artifact (an assignment row or a skill target row). */
export type SyncStatus = 
/**  Row created, sync not yet attempted. */
"pending" | 
/**  Artifact present and (for copies) content matches the source. */
"synced" | 
/**  Copy-mode artifact whose content no longer matches the source. */
"stale" | 
/**  Source or a previously deployed target has disappeared. */
"missing" | 
/**  The last sync/cleanup attempt failed; `last_error` carries the diagnostic. */
"error";

export type SyncTargetResultDto = {
	skill_id: string,
	skill_name: string,
	tool: string,
	status: SyncTargetStatusDto,
};

/**
 *  Per-(skill, tool) result. `skipped` is the expected-and-ignorable class
 *  (tool absent, dir unwritable); `failed` is everything else. Both carry
 *  the typed error so call sites choose what to surface.
 */
export type SyncTargetStatusDto = { status: "synced"; mode_used: SyncMode } | { status: "skipped"; error: CommandError } | { status: "failed"; error: CommandError };

export type ToolInfoDto = {
	key: string,
	label: string,
	installed: boolean,
	/**
	 *  Keys of every listed tool sharing this tool's skills dir (global dir
	 *  for the global list, project dir for the project list), in adapter
	 *  order, including this tool itself (len >= 1). The backend owns the
	 *  shared-dir invariant; the frontend only presents it. The dir itself is
	 *  not on the wire — see `ToolCatalogEntry`.
	 */
	shared_with: string[],
	/**
	 *  Display labels of the constituent tools absorbed into this entry when
	 *  it is a virtual group (project-scope AgentsStandard); empty for real
	 *  tools. The backend owns group membership; the frontend only presents it.
	 */
	constituents: string[],
};

export type ToolStatusDto = {
	tools: ToolInfoDto[],
	installed: string[],
	newly_installed: string[],
};

export type UpdateResultDto = {
	skill_id: string,
	name: string,
	content_hash: string | null,
	source_revision: string | null,
	updated_targets: string[],
};

