// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
	/**
	 *  Persist one setting and return the effective snapshot. `~` in a central
	 *  repo path is expanded here — the only environment-aware step — before
	 *  the policy layer validates and applies it.
	 */
	updateSetting: (update: SettingUpdate) => __TAURI_INVOKE<AppSettings>("update_setting", { update }),
	getToolStatus: () => __TAURI_INVOKE<ToolStatusDto>("get_tool_status"),
	getProjectToolStatus: () => __TAURI_INVOKE<ToolStatusDto>("get_project_tool_status"),
	clearGitCacheNow: () => __TAURI_INVOKE<number>("clear_git_cache_now"),
	getOnboardingPlan: () => __TAURI_INVOKE<OnboardingPlan>("get_onboarding_plan"),
	listLocalSkillsCmd: (basePath: string) => __TAURI_INVOKE<LocalSkillCandidate[]>("list_local_skills_cmd", { basePath }),
	installLocalSelection: (basePath: string, subpath: string, name: string | null) => __TAURI_INVOKE<InstallResultDto>("install_local_selection", { basePath, subpath, name }),
	listGitSkillsCmd: (repoUrl: string, targetName: string | null) => __TAURI_INVOKE<GitSkillListing>("list_git_skills_cmd", { repoUrl, targetName }),
	installGitSelection: (repoUrl: string, subpath: string, name: string | null) => __TAURI_INVOKE<InstallResultDto>("install_git_selection", { repoUrl, subpath, name }),
	/**
	 *  Sync N skills to M tools in one call. The backend owns the whole
	 *  choreography — installedness filtering, shared-dir dedupe, overwrite
	 *  policy, DB record fan-out — and returns a per-target report; per-target
	 *  failures are data, not command errors.
	 */
	syncSkillsToTools: (skills: BatchSyncSkillDto[], tools: string[], policy: BatchSyncPolicyDto, onProgress: Channel<SyncProgressDto>) => __TAURI_INVOKE<BatchSyncReportDto>("sync_skills_to_tools", { skills, tools, policy, onProgress }),
	unsyncSkillFromTool: (skillId: string, tool: string) => __TAURI_INVOKE<RemovalReportDto>("unsync_skill_from_tool", { skillId, tool }),
	/**
	 *  Re-acquire Managed skills from their sources, finalize them, and
	 *  propagate to every Sync target — one batch, one report. `skillIds` of
	 *  `None` means every Managed skill (Refresh all); a single-skill Update is
	 *  a batch of one. Per-skill and per-target failures are report data, not
	 *  command errors.
	 */
	refreshManagedSkills: (skillIds: string[] | null, policy: RefreshPolicyDto, onProgress: Channel<RefreshProgressDto>) => __TAURI_INVOKE<RefreshReportDto>("refresh_managed_skills", { skillIds, policy, onProgress }),
	/**
	 *  Import pre-existing Tool skills the operator selected, in one call: admit
	 *  each chosen variant, finalize it as a Managed skill, then sync it
	 *  (auto-sync on) or remove the byte-identical originals (auto-sync off).
	 *  Per-group, per-target and per-original failures are report data.
	 */
	importOnboardingSelection: (selections: OnboardingSelectionDto[], policy: ImportPolicyDto, onProgress: Channel<ImportProgressDto>) => __TAURI_INVOKE<ImportReportDto>("import_onboarding_selection", { selections, policy, onProgress }),
	getManagedSkills: () => __TAURI_INVOKE<ManagedSkillDto[]>("get_managed_skills"),
	deleteManagedSkill: (skillId: string) => __TAURI_INVOKE<null>("delete_managed_skill", { skillId }),
	unsyncAllSkills: () => __TAURI_INVOKE<RemovalReportDto>("unsync_all_skills"),
	unsyncSkill: (skillId: string) => __TAURI_INVOKE<RemovalReportDto>("unsync_skill", { skillId }),
	getFeaturedSkills: () => __TAURI_INVOKE<FeaturedSkillDto[]>("get_featured_skills"),
	searchSkillsOnline: (query: string, limit: number | null) => __TAURI_INVOKE<OnlineSkillDto[]>("search_skills_online", { query, limit }),
	listSkillFiles: (centralPath: string) => __TAURI_INVOKE<SkillFileEntry[]>("list_skill_files", { centralPath }),
	readSkillFile: (centralPath: string, filePath: string) => __TAURI_INVOKE<string>("read_skill_file", { centralPath, filePath }),
	cloneExploreSkill: (sourceUrl: string, skillName: string | null) => __TAURI_INVOKE<string>("clone_explore_skill", { sourceUrl, skillName }),
	hideExploreSkill: (sourceUrl: string) => __TAURI_INVOKE<null>("hide_explore_skill", { sourceUrl }),
	unhideExploreSkill: (sourceUrl: string) => __TAURI_INVOKE<null>("unhide_explore_skill", { sourceUrl }),
	getHiddenExploreSkills: () => __TAURI_INVOKE<string[]>("get_hidden_explore_skills"),
	cancelCurrentOperation: () => __TAURI_INVOKE<null>("cancel_current_operation"),
	/**
	 *  Reveal the app log file — where `tauri-plugin-log` writes (`LogDir`,
	 *  see `lib.rs`) — selected in its folder in the operator's file manager
	 *  (the folder itself when no file exists yet). The backend log is partial
	 *  forensics for earlier runs — backend-logged events only, not a record of
	 *  what a Notification reported. Both the paths and the opener are resolved
	 *  here at the command seam: `core` never sees the app handle.
	 */
	openLogFolder: () => __TAURI_INVOKE<null>("open_log_folder"),
	registerProject: (path: string) => __TAURI_INVOKE<ProjectViewDto>("register_project", { path }),
	/**
	 *  Remove a project and every artifact it owns. The project it named is
	 *  gone, so the fresh view is the *remaining* project list.
	 */
	removeProject: (projectId: string) => __TAURI_INVOKE<ProjectDto[]>("remove_project", { projectId }),
	listProjects: () => __TAURI_INVOKE<ProjectDto[]>("list_projects"),
	updateProjectPath: (projectId: string, path: string) => __TAURI_INVOKE<ProjectViewDto>("update_project_path", { projectId, path }),
	/**
	 *  Replace the project's configured tool set and, when `gitignore` is given,
	 *  update its ignore files afterwards. Core owns the ordering
	 *  (`project_ops::configure_project_tools`). Removing a tool cascades to its
	 *  assignments, so the returned view already reflects that cascade.
	 */
	configureProjectTools: (projectId: string, tools: string[], gitignore: {
	add_to_gitignore: boolean,
	add_to_exclude: boolean,
} | null) => __TAURI_INVOKE<ProjectViewDto>("configure_project_tools", { projectId, tools, gitignore }),
	/**
	 *  The read counterpart of the mutation views: what selecting a project
	 *  loads.
	 */
	getProjectView: (projectId: string) => __TAURI_INVOKE<ProjectViewDto>("get_project_view", { projectId }),
	/**
	 *  Assign or unassign one skill × project Tool pair — the backend decides
	 *  which from its own rows, so no caller mirrors assignment existence.
	 */
	toggleProjectSkillAssignment: (projectId: string, skillId: string, tool: string) => __TAURI_INVOKE<ToggleAssignmentResultDto>("toggle_project_skill_assignment", { projectId, skillId, tool }),
	resyncProject: (projectId: string) => __TAURI_INVOKE<ResyncProjectResultDto>("resync_project", { projectId }),
	resyncAllProjects: () => __TAURI_INVOKE<ResyncAllResultDto>("resync_all_projects"),
	bulkAssignSkill: (projectId: string, skillId: string) => __TAURI_INVOKE<BulkAssignResultDto>("bulk_assign_skill", { projectId, skillId }),
	updateProjectGitignore: (projectId: string, gitignore: IgnoreUpdateOptions) => __TAURI_INVOKE<null>("update_project_gitignore", { projectId, gitignore }),
	getProjectGitignoreStatus: (projectId: string) => __TAURI_INVOKE<GitignoreStatusDto>("get_project_gitignore_status", { projectId }),
};

/* Types */
/**
 *  Snapshot of every backend-persisted setting, already parsed, defaulted
 *  and (for the central repo path) resolved.
 */
export type AppSettings = {
	/**  Resolved central skills repo root (override or default). */
	central_repo_path: string,
	git_cache_cleanup_days: number,
	git_cache_ttl_secs: number,
	/**  Empty string when no token is stored. */
	github_token: string,
	auto_sync_enabled: boolean,
	/**  `None` = never configured (distinct from an empty selection). */
	global_selected_tools: string[] | null,
	scan_selected_tools_only: boolean,
	/**
	 *  Always finite (clamped into `UI_ZOOM_LEVEL_RANGE`), hence `number`
	 *  rather than specta's default `number | null` for `f64`.
	 */
	ui_zoom_level: number,
	bounds: SettingsBounds,
};

/**
 *  Force-overwrite for one (skill, tool) pair; applies to any target tool
 *  sharing the named tool's skills dir.
 */
export type BatchSyncOverrideDto = {
	skill_id: string,
	tool: string,
	overwrite: boolean,
};

export type BatchSyncPolicyDto = {
	overwrite?: boolean,
	overwrite_if_same_content?: boolean,
	overrides?: BatchSyncOverrideDto[],
};

export type BatchSyncReportDto = {
	results: SyncTargetResultDto[],
	synced: number,
	skipped: number,
	failed: number,
};

/**  One skill in a batch sync request. */
export type BatchSyncSkillDto = {
	skill_id: string,
	name: string,
	source_path: string,
};

export type BulkAssignErrorDto = {
	tool: string,
	error: CommandError,
};

/**
 *  The fan-out's fresh view plus the tools it could not assign. Tools that
 *  were already assigned are silent (nothing changed for them); the view
 *  carries every assignment that now exists.
 */
export type BulkAssignResultDto = {
	view: ProjectViewDto,
	failed: BulkAssignErrorDto[],
};

/**
 *  Wire form of [`SkillMatch`]: candidates are referenced by subpath, the
 *  identity the frontend already keys its selection by.
 */
export type CandidateMatch = { kind: "resolved"; subpath: string } | { kind: "ambiguous"; subpaths: string[] } | { kind: "none" };

/**  Structured command failure crossing the IPC seam. */
export type CommandError = { code: "TOOL_NOT_INSTALLED"; tool: string } | { code: "TARGET_EXISTS"; path: string } | { code: "TOOL_NOT_WRITABLE"; tool: string; path: string } | { code: "SKILL_INVALID"; reason: string } | { code: "MULTI_SKILLS" } | { code: "SKILL_EXISTS"; 
/**  Name of the skill directory already present in the central repo. */
name: string } | { code: "DUPLICATE_PROJECT"; path: string } | { code: "ASSIGNMENT_EXISTS"; project: string; skill: string; tool: string } | { code: "NOT_FOUND"; kind: string; id: string } | { code: "UNKNOWN_TOOL"; 
/**  Registry key that matched no tool adapter. */
tool: string } | { code: "INVALID_PATH"; path: string; 
/**  Machine token (`missing` / `not_a_directory`) the frontend localizes. */
reason: string } | { code: "CANCELLED" } | { code: "RATE_LIMITED"; 
/**  Rounded-up minutes until the limit resets; 0 = unknown. */
resetMinutes: number } | { code: "GIT_CLONE_FAILED"; kind: GitCloneFailureKind; detail: string } | { code: "GITHUB_SKILL_NOT_FOUND"; 
/**  Human-checkable GitHub tree URL for the missing skill path. */
url: string } | { code: "DELETE_CLEANUP_FAILED"; 
/**  `"<path>: <io error>"` diagnostics per failed removal target. */
failures: string[] } | { code: "PATH_OUTSIDE_TOOL_DIRS"; 
/**  The refused path (not inside any Tool's skills directory). */
path: string } | { code: "OTHER"; message: string };

export type FeaturedSkillDto = {
	slug: string,
	name: string,
	summary: string,
	downloads: number,
	stars: number,
	source_url: string,
};

/**
 *  Inclusive float bound, shipped to the frontend inside `AppSettings`.
 * 
 *  specta types `f64` as `number | null` because serde_json writes
 *  NaN/±Infinity as `null`; these bounds are finite constants, so the
 *  field-level override asserts the plain `number` the frontend clamps with.
 */
export type FloatRange = {
	min: number,
	max: number,
};

/**
 *  Why a GitHub clone/fetch failed, classified backend-side from the error
 *  chain (the backend has the chain; the frontend owns the copy).
 */
export type GitCloneFailureKind = "tls" | "auth" | "notFound" | "dns" | "timeout" | "refused" | 
/**  Running the system `git` CLI itself failed (fallback disabled). */
"execFailed" | "unknown";

export type GitSkillCandidate = {
	name: string,
	description: string | null,
	subpath: string,
};

/**
 *  What the git add flow gets back from a listing: the candidates plus, when
 *  the caller named the skill it is after (Explore install), that name
 *  resolved against them by the one core matching rule.
 */
export type GitSkillListing = {
	candidates: GitSkillCandidate[],
	/**  `None` when no `target_name` was given. */
	target_match: CandidateMatch | null,
};

export type GitignoreStatusDto = {
	in_gitignore: boolean,
	in_exclude: boolean,
};

/**
 *  The two toggles behind `update_project_gitignore`; also the optional
 *  ignore intent carried by `configure_project_tools`, hence an IPC DTO.
 */
export type IgnoreUpdateOptions = {
	add_to_gitignore: boolean,
	add_to_exclude: boolean,
};

export type ImportGroupOutcomeDto = {
	group_name: string,
	status: ImportGroupStatusDto,
};

/**
 *  Per-group result. `targets` carries the sync outcomes (auto-sync on) and
 *  `originals` the settled originals (auto-sync off); the other is empty.
 *  `forced_source_tool` names the Tool the chosen variant was found in when
 *  it was synced beyond the policy's Tools (so its original is overwritten
 *  in place rather than left as an untracked copy); `null` otherwise.
 */
export type ImportGroupStatusDto = { status: "imported"; skill_id: string; skill_name: string; targets: SyncTargetResultDto[]; forced_source_tool: string | null; originals: ImportOriginalDto[] } | { status: "failed"; error: CommandError };

export type ImportOriginalDto = {
	path: string,
	tool: string,
	status: ImportOriginalStatusDto,
};

/**
 *  What happened to one original directory (auto-sync off). `kept_divergent`
 *  means the directory's content differs from the imported skill, so it was
 *  deliberately left in place — report data, not a command error.
 */
export type ImportOriginalStatusDto = { status: "removed" } | { status: "kept_divergent" } | { status: "failed"; error: CommandError };

export type ImportPhaseDto = "admitting" | "applying";

/**
 *  What happens to the originals: sync the imported skill to `tools`
 *  (`None` = every installed Tool), or remove the originals.
 */
export type ImportPolicyDto = {
	auto_sync?: boolean,
	tools?: string[] | null,
};

/**  Progress tick streamed before each phase of each imported group. */
export type ImportProgressDto = {
	index: number,
	total: number,
	group_name: string,
	phase: ImportPhaseDto,
};

export type ImportReportDto = {
	groups: ImportGroupOutcomeDto[],
	imported: number,
	failed: number,
};

export type InstallResultDto = {
	skill_id: string,
	name: string,
	central_path: string,
	content_hash: string | null,
};

/**  Inclusive integer bound, shipped to the frontend inside `AppSettings`. */
export type IntRange = {
	min: number,
	max: number,
};

/**
 *  Who may invoke a skill, derived from its `SKILL.md` frontmatter.
 * 
 *  Two Claude Code frontmatter keys govern this (the agentskills.io
 *  specification does not define them yet):
 *  `disable-model-invocation: true` blocks automatic model invocation, and
 *  `user-invocable: false` hides the skill from the `/` menu. Both default to
 *  the permissive value, so a skill with no frontmatter — or with malformed
 *  frontmatter — is [`InvocationMode::UserAndModel`]. Setting both keys is the
 *  documented recipe for hiding a skill from everyone: [`InvocationMode::Neither`].
 */
export type InvocationMode = 
/**  Default: the user can type `/name` and the model can load it on its own. */
"user-and-model" | 
/**  `disable-model-invocation: true` — only the user can invoke it. */
"user-only" | 
/**  `user-invocable: false` — only the model can invoke it. */
"model-only" | 
/**  Both keys restrict invocation — neither the user nor the model can invoke it. */
"neither";

export type LocalSkillCandidate = {
	name: string,
	description: string | null,
	subpath: string,
	valid: boolean,
	reason: string | null,
};

export type ManagedSkillDto = {
	id: string,
	name: string,
	description: string | null,
	source_type: string,
	source_ref: string | null,
	central_path: string,
	created_at: number,
	updated_at: number,
	last_sync_at: number | null,
	status: string,
	/**
	 *  Who may invoke the skill, read from the central copy's `SKILL.md`
	 *  frontmatter at list time (not persisted).
	 */
	invocation_mode: InvocationMode,
	targets: SkillTargetDto[],
};

export type OnboardingGroup = {
	name: string,
	variants: OnboardingVariant[],
	has_conflict: boolean,
};

export type OnboardingPlan = {
	total_tools_scanned: number,
	total_skills_found: number,
	groups: OnboardingGroup[],
};

/**
 *  One name-group the operator chose to import. The backend re-reads the
 *  onboarding plan to learn which paths the group owns, so this carries only
 *  the choice itself.
 */
export type OnboardingSelectionDto = {
	group_name: string,
	chosen_path: string,
	name: string | null,
};

export type OnboardingVariant = {
	tool: string,
	name: string,
	path: string,
	fingerprint: string | null,
	is_link: boolean,
	link_target: string | null,
};

export type OnlineSkillDto = {
	name: string,
	installs: number,
	source: string,
	source_url: string,
};

export type ProjectDto = {
	id: string,
	path: string,
	name: string,
	created_at: number,
	updated_at: number,
	tool_count: number,
	skill_count: number,
	assignment_count: number,
	sync_status: ProjectSyncStatus,
	path_exists: boolean,
};

export type ProjectSkillAssignmentDto = {
	id: string,
	project_id: string,
	skill_id: string,
	skill_name: string,
	tool: string,
	mode: SyncMode,
	status: SyncStatus,
	last_error: string | null,
	synced_at: number | null,
	content_hash: string | null,
	created_at: number,
};

/**
 *  Roll-up of a project's assignments as shown on the project list.
 *  `Missing` folds into `Error` (both need the user's attention).
 */
export type ProjectSyncStatus = 
/**  No assignments at all. */
"none" | "error" | "stale" | "pending" | "synced";

export type ProjectToolDto = {
	id: string,
	project_id: string,
	tool: string,
};

/**
 *  Everything the project world shows for one project, as one wire value:
 *  the project row (counts and aggregate status included), its configured
 *  Tools, and its assignments with the reconcile flag.
 * 
 *  Every project mutation returns this, so the frontend applies one result
 *  instead of chasing the mutation with follow-up reads. It is always built
 *  *after* the mutation released the mutation guard, so its reconcile pass
 *  can take the guard normally.
 */
export type ProjectViewDto = {
	project: ProjectDto,
	tools: ProjectToolDto[],
	assignments: ProjectSkillAssignmentDto[],
	/**
	 *  `false` means a Sync-target mutation was in flight and the reconcile
	 *  pass was skipped rather than queued: the rows are the stored ones,
	 *  not re-derived from disk. Never read it as healthy.
	 */
	reconciled: boolean,
};

/**  Which Sync target a Propagation outcome is about. */
export type PropagationScopeDto = { scope: "global"; tool: string } | { scope: "project"; project_id: string; tool: string };

/**
 *  Why a Sync target needed no work. Not a failure — skipping is the correct
 *  outcome for a link, an uninstalled Tool, or an absent Project.
 */
export type PropagationSkipDto = { reason: "link_follows_source" } | { reason: "tool_not_installed"; tool: string } | { reason: "unknown_tool"; tool: string } | { reason: "project_unavailable"; project_id: string };

export type PropagationStatusDto = { status: "synced"; mode_used: SyncMode } | { status: "skipped"; reason: PropagationSkipDto } | { status: "failed"; error: CommandError };

export type PropagationTargetDto = {
	scope: PropagationScopeDto,
	status: PropagationStatusDto,
};

export type RefreshPhaseDto = "acquiring" | "applying";

export type RefreshPolicyDto = {
	/**
	 *  Also sync each refreshed skill to installed Tools it is not on yet
	 *  (the auto-sync invariant, re-asserted). The caller decides — the
	 *  backend never reads the auto-sync setting behind its back.
	 */
	reassert_auto_sync?: boolean,
};

/**  Progress tick streamed before each per-skill step of each Refresh phase. */
export type RefreshProgressDto = {
	index: number,
	total: number,
	skill_name: string,
	phase: RefreshPhaseDto,
};

export type RefreshReportDto = {
	skills: SkillRefreshResultDto[],
	refreshed: number,
	failed: number,
	/**
	 *  Sync targets that failed across every refreshed skill. A failed
	 *  auto-sync re-assert counts as one.
	 */
	target_failures: number,
};

export type RemovalReportDto = {
	targets: RemovalTargetDto[],
	/**  Rows whose artifact was removed (and whose row was deleted). */
	removed: number,
	/**  Rows kept with Sync status `error` because their artifact stayed. */
	failed: number,
};

/**  Which Sync target a removal outcome is about. */
export type RemovalScopeDto = { scope: "global" } | { scope: "project"; project_id: string };

export type RemovalTargetDto = {
	scope: RemovalScopeDto,
	tool: string,
	path: string,
	status: RemovalTargetStatusDto,
};

/**
 *  Per-row removal result. `failed` means the artifact is still on disk and
 *  the row was kept with Sync status `error` (ADR-0002) — report data, not a
 *  command error.
 */
export type RemovalTargetStatusDto = { status: "removed" } | { status: "failed"; error: CommandError };

/**
 *  Per-project counts and errors plus the refreshed project list. A single
 *  project's assignments are not returned here — the caller re-reads the
 *  view of whichever project it is showing.
 */
export type ResyncAllResultDto = {
	summaries: ResyncSummaryDto[],
	projects: ProjectDto[],
};

/**  A resync's counts and errors alongside the project's fresh view. */
export type ResyncProjectResultDto = {
	view: ProjectViewDto,
	summary: ResyncSummaryDto,
};

export type ResyncSummaryDto = {
	project_id: string,
	synced: number,
	failed: number,
	errors: string[],
};

/**  One setting write, as sent by the frontend: `{ key, value }`. */
export type SettingUpdate = 
/**
 *  Absolute path; `~` expansion happens at the command seam. Moving the
 *  repo relocates every managed skill directory.
 */
{ key: "central_repo_path"; value: string } | 
/**  Clamped into `GIT_CACHE_CLEANUP_DAYS_RANGE`. */
{ key: "git_cache_cleanup_days"; value: number } | 
/**  Clamped into `GIT_CACHE_TTL_SECS_RANGE`. */
{ key: "git_cache_ttl_secs"; value: number } | 
/**  Trimmed; blank clears the token. */
{ key: "github_token"; value: string } | { key: "auto_sync_enabled"; value: boolean } | { key: "global_tool_config"; value: {
	selected_tools: string[],
	scan_selected_only: boolean,
} } | 
/**
 *  Clamped into `UI_ZOOM_LEVEL_RANGE`; non-finite falls back to default.
 *  Typed `number` (not specta's `number | null` for `f64`): `null` would
 *  fail deserialization, so it is not a value the frontend may send.
 */
{ key: "ui_zoom_level"; value: number };

/**  Every bound the frontend needs to clamp input before sending it. */
export type SettingsBounds = {
	git_cache_cleanup_days: IntRange,
	git_cache_ttl_secs: IntRange,
	ui_zoom_level: FloatRange,
};

export type SkillFileEntry = {
	path: string,
	size: number,
};

export type SkillRefreshResultDto = {
	skill_id: string,
	skill_name: string,
	status: SkillRefreshStatusDto,
};

/**
 *  Per-skill result of a Refresh batch. A skill whose bytes could not be
 *  acquired is `failed` — its Sync targets were left alone.
 */
export type SkillRefreshStatusDto = { status: "refreshed"; content_hash: string | null; source_revision: string | null; targets: PropagationTargetDto[]; 
/**
 *  A store failure inside the auto-sync re-assert. The skill is still
 *  `refreshed`; the targets the re-assert would have created are
 *  unknown, so this counts as one `target_failures`.
 */
reassert_error: CommandError | null } | { status: "failed"; error: CommandError };

export type SkillTargetDto = {
	tool: string,
	mode: SyncMode,
	status: SyncStatus,
	target_path: string,
	synced_at: number | null,
};

/**
 *  How an artifact was materialised. Stored on the row so a later pass knows
 *  whether content drift is possible (copies) or not (links).
 */
export type SyncMode = "symlink" | 
/**  Windows directory junction (the symlink fallback). */
"junction" | "copy";

/**
 *  Progress tick streamed over the command's channel before each attempted
 *  (skill, tool) pair.
 */
export type SyncProgressDto = {
	index: number,
	total: number,
	skill_name: string,
	tool: string,
};

/**  Lifecycle of one synced artifact (an assignment row or a skill target row). */
export type SyncStatus = 
/**  Row created, sync not yet attempted. */
"pending" | 
/**  Artifact present and (for copies) content matches the source. */
"synced" | 
/**  Copy-mode artifact whose content no longer matches the source. */
"stale" | 
/**  Source or a previously deployed target has disappeared. */
"missing" | 
/**  The last sync or Artifact removal attempt failed; `last_error` carries the diagnostic. */
"error";

export type SyncTargetResultDto = {
	skill_id: string,
	skill_name: string,
	tool: string,
	status: SyncTargetStatusDto,
};

/**
 *  Per-(skill, tool) result. `skipped` is the expected-and-ignorable class
 *  (tool absent, dir unwritable); `failed` is everything else. Both carry
 *  the typed error so call sites choose what to surface.
 */
export type SyncTargetStatusDto = { status: "synced"; mode_used: SyncMode } | { status: "skipped"; error: CommandError } | { status: "failed"; error: CommandError };

/**  Which way a toggle went, with the resulting view. */
export type ToggleAssignmentResultDto = {
	view: ProjectViewDto,
	/**
	 *  True when the skill is now assigned to the tool, false when the
	 *  assignment was removed.
	 */
	assigned: boolean,
};

export type ToolInfoDto = {
	key: string,
	label: string,
	installed: boolean,
	/**
	 *  Keys of every listed tool sharing this tool's skills dir (global dir
	 *  for the global list, project dir for the project list), in adapter
	 *  order, including this tool itself (len >= 1). The backend owns the
	 *  shared-dir invariant; the frontend only presents it. The dir itself is
	 *  not on the wire — see `ToolCatalogEntry`.
	 */
	shared_with: string[],
	/**
	 *  Display labels of the constituent tools absorbed into this entry when
	 *  it is a virtual group (project-scope AgentsStandard); empty for real
	 *  tools. The backend owns group membership; the frontend only presents it.
	 */
	constituents: string[],
};

export type ToolStatusDto = {
	tools: ToolInfoDto[],
	installed: string[],
	newly_installed: string[],
};

