// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallResultDto = { skill_id: string, name: string, central_path: string, content_hash: string | null, };
