// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inclusive integer bound, shipped to the frontend inside `AppSettings`.
 */
export type IntRange = { min: number, max: number, };
