// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalSkillCandidate = { name: string, description: string | null, subpath: string, valid: boolean, reason: string | null, };
