// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillTargetDto } from "./SkillTargetDto";

export type ManagedSkillDto = { id: string, name: string, description: string | null, source_type: string, source_ref: string | null, central_path: string, created_at: number, updated_at: number, last_sync_at: number | null, status: string, targets: Array<SkillTargetDto>, };
