// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnboardingVariant = { tool: string, name: string, path: string, fingerprint: string | null, is_link: boolean, link_target: string | null, };
