// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingGroup } from "./OnboardingGroup";

export type OnboardingPlan = { total_tools_scanned: number, total_skills_found: number, groups: Array<OnboardingGroup>, };
