// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingVariant } from "./OnboardingVariant";

export type OnboardingGroup = { name: string, variants: Array<OnboardingVariant>, has_conflict: boolean, };
