// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Roll-up of a project's assignments as shown on the project list.
 * `Missing` folds into `Error` (both need the user's attention).
 */
export type ProjectSyncStatus = "none" | "error" | "stale" | "pending" | "synced";
