// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSyncStatus } from "./ProjectSyncStatus";

export type ProjectDto = { id: string, path: string, name: string, created_at: number, updated_at: number, tool_count: number, skill_count: number, assignment_count: number, sync_status: ProjectSyncStatus, path_exists: boolean, };
