// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSkillAssignmentDto = { id: string, project_id: string, skill_id: string, skill_name: string, tool: string, mode: string, status: string, last_error: string | null, synced_at: number | null, content_hash: string | null, created_at: number, };
