// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FloatRange } from "./FloatRange";
import type { IntRange } from "./IntRange";

/**
 * Every bound the frontend needs to clamp input before sending it.
 */
export type SettingsBounds = { git_cache_cleanup_days: IntRange, git_cache_ttl_secs: IntRange, ui_zoom_level: FloatRange, };
