// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One setting write, as sent by the frontend: `{ key, value }`.
 */
export type SettingUpdate = { "key": "central_repo_path", "value": string } | { "key": "git_cache_cleanup_days", "value": number } | { "key": "git_cache_ttl_secs", "value": number } | { "key": "github_token", "value": string } | { "key": "auto_sync_enabled", "value": boolean } | { "key": "global_tool_config", "value": { selected_tools: Array<string>, scan_selected_only: boolean, } } | { "key": "ui_zoom_level", "value": number };
