// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncMode } from "./SyncMode";
import type { SyncStatus } from "./SyncStatus";

export type SkillTargetDto = { tool: string, mode: SyncMode, status: SyncStatus, target_path: string, synced_at: number | null, };
