// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillTargetDto = { tool: string, mode: string, status: string, target_path: string, synced_at: number | null, };
