// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress tick streamed over the command's channel before each attempted
 * (skill, tool) pair.
 */
export type SyncProgressDto = { index: number, total: number, skill_name: string, tool: string, };
