// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of one synced artifact (an assignment row or a skill target row).
 */
export type SyncStatus = "pending" | "synced" | "stale" | "missing" | "error";
