// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncTargetStatusDto } from "./SyncTargetStatusDto";

export type SyncTargetResultDto = { skill_id: string, skill_name: string, tool: string, status: SyncTargetStatusDto, };
