// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an artifact was materialised. Stored on the row so a later pass knows
 * whether content drift is possible (copies) or not (links).
 */
export type SyncMode = "symlink" | "junction" | "copy";
