// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandError } from "./CommandError";

/**
 * Per-(skill, tool) result. `skipped` is the expected-and-ignorable class
 * (tool absent, dir unwritable); `failed` is everything else. Both carry
 * the typed error so call sites choose what to surface.
 */
export type SyncTargetStatusDto = { "status": "synced", mode_used: string, } | { "status": "skipped", error: CommandError, } | { "status": "failed", error: CommandError, };
