// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolInfoDto } from "./ToolInfoDto";

export type ToolStatusDto = { tools: Array<ToolInfoDto>, installed: Array<string>, newly_installed: Array<string>, };
