// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolInfoDto = { key: string, label: string, installed: boolean, skills_dir: string, 
/**
 * Keys of every listed tool sharing this tool's skills dir (global dir
 * for the global list, project dir for the project list), in adapter
 * order, including this tool itself (len >= 1). The backend owns the
 * shared-dir invariant; the frontend only presents it.
 */
shared_with: Array<string>, 
/**
 * Display labels of the constituent tools absorbed into this entry when
 * it is a virtual group (project-scope AgentsStandard); empty for real
 * tools. The backend owns group membership; the frontend only presents it.
 */
constituents: Array<string>, };
