// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolInfoDto = { key: string, label: string, installed: boolean, skills_dir: string, 
/**
 * Keys of every global tool sharing this tool's skills dir, in adapter
 * order, including this tool itself (len >= 1). The backend owns the
 * shared-dir invariant; the frontend only presents it.
 */
shared_with: Array<string>, };
