// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateResultDto = { skill_id: string, name: string, content_hash: string | null, source_revision: string | null, updated_targets: Array<string>, };
