// IPC DTO types are generated by tauri-specta from the Rust structs into
// src/bindings/index.ts (regenerated by `cargo test`, committed, CI
// diff-guarded).
// This shim is the single import home for the skills world: components
// import from here, never from src/bindings/ directly.

export type { OnboardingVariant } from "../../bindings";
export type { OnboardingGroup } from "../../bindings";
export type { OnboardingPlan } from "../../bindings";
// Aliased: the frontend has always called this ManagedSkill; the Rust
// struct (and generated binding) is ManagedSkillDto.
export type { ManagedSkillDto as ManagedSkill } from "../../bindings";
export type { SkillTargetDto } from "../../bindings";
export type { InvocationMode } from "../../bindings";
export type { SyncStatus } from "../../bindings";
export type { SyncMode } from "../../bindings";
export type { GitSkillCandidate } from "../../bindings";
export type { GitSkillListing } from "../../bindings";
export type { CandidateMatch } from "../../bindings";
export type { LocalSkillCandidate } from "../../bindings";
export type { InstallResultDto } from "../../bindings";
export type { UpdateResultDto } from "../../bindings";
export type { AppSettings } from "../../bindings";
export type { SettingUpdate } from "../../bindings";
export type { SettingsBounds } from "../../bindings";
export type { FeaturedSkillDto } from "../../bindings";
export type { OnlineSkillDto } from "../../bindings";
export type { SkillFileEntry } from "../../bindings";
export type { ToolInfoDto } from "../../bindings";
export type { ToolStatusDto } from "../../bindings";
export type { BatchSyncSkillDto } from "../../bindings";
export type { BatchSyncOverrideDto } from "../../bindings";
export type { BatchSyncPolicyDto } from "../../bindings";
export type { BatchSyncReportDto } from "../../bindings";
export type { SyncTargetResultDto } from "../../bindings";
export type { SyncTargetStatusDto } from "../../bindings";
export type { SyncProgressDto } from "../../bindings";

// Frontend-only type (no Rust counterpart).
export type ToolOption = {
  id: string;
  label: string;
};
