// IPC DTO types are generated by tauri-specta from the Rust structs into
// src/bindings/index.ts (regenerated by `cargo test`, committed, CI
// diff-guarded).
// This shim is the single import home for the skills world: components
// import from here, never from src/bindings/ directly.

export type { OnboardingVariant } from "../../bindings";
export type { OnboardingGroup } from "../../bindings";
export type { OnboardingPlan } from "../../bindings";
// Aliased: the frontend has always called this ManagedSkill; the Rust
// struct (and generated binding) is ManagedSkillDto.
export type { ManagedSkillDto as ManagedSkill } from "../../bindings";
export type { SkillTargetDto } from "../../bindings";
export type { InvocationMode, InvocationOverride } from "../../bindings";
export type { SyncStatus } from "../../bindings";
export type { SyncMode } from "../../bindings";
export type { GitSkillCandidate } from "../../bindings";
export type { GitSourceResolution } from "../../bindings";
export type { GitSkillListing } from "../../bindings";
export type { CandidateMatch } from "../../bindings";
export type { LocalSkillCandidate } from "../../bindings";
export type { InstallResultDto } from "../../bindings";
export type { RefreshReport } from "../../bindings";
export type { SkillMutationResultDto, InvocationEditResultDto, InvocationEditReport } from "../../bindings";
export type { RefreshPolicyDto } from "../../bindings";
export type { RefreshProgressDto } from "../../bindings";
export type { SkillRefreshOutcome } from "../../bindings";
export type { SkillRefreshStatus } from "../../bindings";
export type { UnlocatableState, UpdateSkip } from "../../bindings";
export type { PropagationOutcome, PropagationReport } from "../../bindings";
export type { PropagationScope } from "../../bindings";
export type { PropagationStatus } from "../../bindings";
export type { PropagationSkip } from "../../bindings";
export type { AppSettings } from "../../bindings";
export type { SettingUpdate } from "../../bindings";
export type { SettingsBounds } from "../../bindings";
export type { FeaturedSkillDto } from "../../bindings";
export type { OnlineSkillDto } from "../../bindings";
export type { SkillFileEntry } from "../../bindings";
export type { ToolInfoDto } from "../../bindings";
export type { ToolStatusDto } from "../../bindings";
export type { BatchSyncSkillDto } from "../../bindings";
export type { BatchSyncOverrideDto } from "../../bindings";
export type { BatchSyncPolicyDto } from "../../bindings";
export type { BatchTargetOutcome } from "../../bindings";
export type { BatchTargetStatus } from "../../bindings";
export type { SyncProgressDto } from "../../bindings";
export type { RemovalReport } from "../../bindings";
export type { RemovalTargetOutcome } from "../../bindings";
export type { RowRef } from "../../bindings";
export type { RemovalTargetStatus } from "../../bindings";
export type { OnboardingSelectionDto } from "../../bindings";
export type { ImportPolicyDto } from "../../bindings";
export type { ImportProgressDto } from "../../bindings";
export type { ImportReport } from "../../bindings";
export type { ImportGroupOutcome } from "../../bindings";
export type { ImportGroupStatus } from "../../bindings";
export type { OriginalOutcome } from "../../bindings";
export type { OriginalStatus } from "../../bindings";

// Frontend-only type (no Rust counterpart).
export type ToolOption = {
  id: string;
  label: string;
};
