export type OnboardingVariant = {
  tool: string;
  name: string;
  path: string;
  fingerprint?: string | null;
  is_link: boolean;
  link_target?: string | null;
};

export type OnboardingGroup = {
  name: string;
  variants: OnboardingVariant[];
  has_conflict: boolean;
};

export type OnboardingPlan = {
  total_tools_scanned: number;
  total_skills_found: number;
  groups: OnboardingGroup[];
};

export type ToolOption = {
  id: string;
  label: string;
};

export type ManagedSkill = {
  id: string;
  name: string;
  description?: string | null;
  source_type: string;
  source_ref?: string | null;
  central_path: string;
  created_at: number;
  updated_at: number;
  last_sync_at?: number | null;
  status: string;
  targets: {
    tool: string;
    mode: string;
    status: string;
    target_path: string;
    synced_at?: number | null;
  }[];
};

export type GitSkillCandidate = {
  name: string;
  description?: string | null;
  subpath: string;
};

export type LocalSkillCandidate = {
  name: string;
  description?: string | null;
  subpath: string;
  valid: boolean;
  reason?: string | null;
};

export type InstallResultDto = {
  skill_id: string;
  name: string;
  central_path: string;
  content_hash?: string | null;
};

// Generated by ts-rs from the Rust DTOs (see src/bindings/); re-exported
// here so component imports keep a single home while the hand-mirror is
// retired (v-next ticket 07).
export type { ToolInfoDto } from "../../bindings/ToolInfoDto";
export type { ToolStatusDto } from "../../bindings/ToolStatusDto";
export type { BatchSyncSkillDto } from "../../bindings/BatchSyncSkillDto";
export type { BatchSyncOverrideDto } from "../../bindings/BatchSyncOverrideDto";
export type { BatchSyncPolicyDto } from "../../bindings/BatchSyncPolicyDto";
export type { BatchSyncReportDto } from "../../bindings/BatchSyncReportDto";
export type { SyncTargetResultDto } from "../../bindings/SyncTargetResultDto";
export type { SyncTargetStatusDto } from "../../bindings/SyncTargetStatusDto";
export type { SyncProgressDto } from "../../bindings/SyncProgressDto";

export type GlobalToolConfigDto = {
  selected_tools: string[] | null;
  scan_selected_only: boolean;
};

export type UpdateResultDto = {
  skill_id: string;
  name: string;
  content_hash?: string | null;
  source_revision?: string | null;
  updated_targets: string[];
};

export type FeaturedSkillDto = {
  slug: string;
  name: string;
  summary: string;
  downloads: number;
  stars: number;
  source_url: string;
};

export type OnlineSkillDto = {
  name: string;
  installs: number;
  source: string;
  source_url: string;
};

export type SkillFileEntry = {
  path: string;
  size: number;
};
